 ---
title: "Análise Exploratória dos Dados"
author: "Seu Nome"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
# Carregar pacotes necessários
library(dplyr)
library(ggplot2)
library(openxlsx) 
library(summarytools)
library(readxl)
library(ggplot2)
library(skimr)
library(corrplot)
library(Amelia)

setwd("C:/Users/MUVA/OneDrive - ASSOCIAÇÃO PARA O EMPODERAMENTO DA RAPARIGA-MUVA/Arquivo DERCIO/Monografia/")
dados_Limpes_INPD <- read_excel("scripts/dados_Limpes_INPD.xlsx")

# Passo 1: Substituir -9 por NA
dados_Limpes_INPD$temp[dados_Limpes_INPD$temp == -9] <- NA

# Passo 3: Substituir NA's pela mediana da temperatura
dados_Limpes_INPD$temp[is.na(dados_Limpes_INPD$temp)] <- median(dados_Limpes_INPD$temp, na.rm = TRUE)

# Passo 3: Substituir NA's pela mediana da temperatura
dados_Limpes_INPD$temp[is.na(dados_Limpes_INPD$temp)] <- median(dados_Limpes_INPD$temp, na.rm = TRUE)
```
 
 
1. Estatísticas Descritivas
```{r}
# Criar um dataframe de exemplo
 # Estatísticas descritivas das variáveis numéricas
summary(dados_Limpes_INPD)

# Estatísticas detalhadas das variáveis numéricas
descr(dados_Limpes_INPD, transpose = TRUE)

```
 
 


 