---
title: "Aquisição e Pré-processamento dos Dados"
output: html_document
---

## Aquisição e Pré-processamento dos Dados

### Carregar a base de dados **INPD4**

```{r}
# Carregar pacotes necessários
library(tidyverse)
library(readr)
library(dplyr)

# Carregar os dados 
setwd("C:/Users/MUVA/OneDrive - ASSOCIAÇÃO PARA O EMPODERAMENTO DA RAPARIGA-MUVA/Arquivo DERCIO/Monografia/")

 dados <- read_csv("data/Dados_inpd4_limpo.csv")

```

# Tratar valores ausentes e inconsistências

```{r}
# Excluir linhas onde 'perm_id' é NA
dados <- dados %>%
  filter(!is.na(perm_id))

 
# Tratar os valores ausentes nas colunas categoricas 
# Função para calcular a moda
moda <- function(x) {
  uniq_x <- table(x)
  moda_val <- names(uniq_x)[which.max(uniq_x)]
  return(moda_val)
}

summary(dados)
```

# Vamos fazer tratamento para cada variavel 

## Variavel Sexo

```{r}
dados$sex <- as.factor(dados$sex)
summary(dados$sex)  # Verificar se ficou correcto

moda <- names(which.max(table(dados$sex, useNA = "no")))
dados$sex[is.na(dados$sex)] <- moda
summary(dados$sex)
```

## Variavel region_nam
```{r}
dados$region_nam <- as.factor(dados$region_nam)
summary(dados$region_nam)  # Verificar se ficou correcto

moda <- names(which.max(table(dados$region_nam, useNA = "no")))
dados$region_nam[is.na(dados$region_nam)] <- moda
summary(dados$region_nam)
```

## day_birth, mon_birth, yea_birth que foram retirados de data de nascimento

```{r}
# Substituir -9 por NA

dados$day_birth[dados$day_birth < 0] <- NA
dados$day_birth[dados$day_birth > 31] <- NA

dados$mon_birth[dados$mon_birth < 1] <- NA
dados$mon_birth[dados$mon_birth > 12] <- NA

dados$yea_birth[dados$yea_birth < 1988] <- NA

# Calcular a mediana ignorando os NA
mediana_day <- median(dados$day_birth, na.rm = TRUE)
mediana_mon <- median(dados$mon_birth, na.rm = TRUE)
mediana_yea <- median(dados$yea_birth, na.rm = TRUE)

# Substituir NA pela mediana
dados$day_birth[is.na(dados$day_birth)] <- mediana_day
dados$mon_birth[is.na(dados$mon_birth)] <- mediana_mon
dados$yea_birth[is.na(dados$yea_birth)] <- mediana_yea

# Verificar se os dados foram tratados corretamente
summary(dados[, c("day_birth", "mon_birth", "yea_birth")])
```
 